### PR TITLE
Replace 'UTF-8' with `encoding` variable

### PR DESCRIPTION
**Pull request by k4y3ff**
This does literally _nothing_ different or useful, but I've been trying my hand at writing a plugin--with this source as a reference--and it's been bothering me all day. ;)

### CODE REVIEW

**Comment by rundis** [comment]
:) 
you might not have picked the simplest plugin as a references source though. 
I've done a couple of different plugins by now, so If you need any help feel free to drop by the LightTable IRC channel on freenode, alternatively the google group: https://groups.google.com/forum/#!forum/light-table-discussion

cheers
- magnus

**Comment by kpfell** [comment]
@rundis Is there a plugin other than Clojure, Python, Groovy, or Haskell that you'd recommend using as a reference?

**Comment by rundis** [comment]
Well it depends on what your ambitions are :) if you are planning to create a language plugin, the ones you mention are good references I suppose.

**Comment by kpfell** [comment]
Ah, yeah, I'm writing a language plugin for Scala. Soooooo. Hahaha.

**Comment by rundis** [comment]
Cool, that would be really nice ! 
Writing this groovy plugin was my entry point to the clojure(script). Great learning experience (and loss of some hair as well)

**Comment by kpfell** [comment]
Oh, yay!

Yeah, I've done Clojure, but I'm not really a front-end developer at all, so I haven't done much of any ClojureScript.

It's pretty fun, though! \o/

**Pull request closed without merging**
